### ISSUE TITLE
Namespace for EnumerableExtensions causes conflicts

### ISSUE THREAD

**Issue by starkcolin** [aloneguid/support#8]
Using the System.Collections.Generic namespace for your EnumerableExtensions methods has caused a conflict with identically named support methods in my own libraries.
It is recommended to not use the System namespace for any libraries that are not part of the framework. ([link 1](https://softwareengineering.stackexchange.com/questions/57294/adding-to-the-system-namespace-in-c), [link 2](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces))
Would it be possible to move these to a unique namespace, say NetBox.Extensions?
My choice now is to either replace all usages of AddRange and ForEach extension methods with fully qualified static methods, or to stop using Config.NET (neither of which is an ideal solution)

**Comment by aloneguid** [comment]
Hi @starkcolin yes you have a valid point, they should go to a separate namespace, it's there mostly for historical reasons ) I will also try to remove Netbox from config.net completely.

**Comment by aloneguid** [comment]
Hi @starkcolin good news - Netbox dependency completely removed from Config.NET, so you should be all safe.

**Comment by starkcolin** [comment]
Thanks! Is this change on NuGet yet?

**Comment by aloneguid** [comment]
@starkcolin config.net changes are
