### ISSUE TITLE
"Strong name could not be verified" on version 2.2.3+

### ISSUE THREAD

**Issue by jonscheiding** [aloneguid/support#9]
I installed `Storage.NET@7.1.17` which pulled in a dependency on `NetBox@2.3.4`.  My application is failing now with the error:

```
Could not load file or assembly 'NetBox' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
```

The assembly does have a public key token and does not appear to be delay signed, but to actually have an invalid signature:

```
.\netbox.2.3.4\lib\netstandard2.0> [System.Reflection.AssemblyName]::GetAssemblyName("$(pwd)\NetBox.dll").FullName
NetBox, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8dea52f811e261ef
.\netbox.2.3.4\lib\netstandard2.0> sn -f .\NetBox.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.
```

The latest version that doesn't have this issue is 2.1.8:

```
.\netbox.2.1.8\lib\netstandard2.0> [System.Reflection.AssemblyName]::GetAssemblyName("$(pwd)\NetBox.dll").FullName
NetBox, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8dea52f811e261ef
.\netbox.2.1.8\lib\netstandard2.0> sn -v .\NetBox.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly '.\NetBox.dll' is valid
```

**Comment by aloneguid** [comment]
thanks for details @jonscheiding it heally helped, looks like `<PublicSign>` was present in csproj which prevented from generating a proper strong name. Previous versions were built on Windows and since migrating build/release pipeline to Ubuntu looks like there is a difference.

![image](https://user-images.githubusercontent.com/3155189/62353078-aaffdb00-b501-11e9-9a44-e1617a0da43f.png)

**Comment by jonscheiding** [comment]
Nice, thanks for the quick turnaround!  Latest version validates successfully for me.

**Comment by aloneguid** [comment]
great, thank you
